### PR TITLE
Various edits

### PR DESCRIPTION
**Pull request by tcoulter**
Updates from @DiscRiskandBisque: 

* Global
    * Slightly altered blog/tutorial card styling for higher contrast. Previously blue text is now black, with read more bolded, since it's the action.
    * Unified transition times when hovering tutorial and blog cards.
    * Various spacing adjustments for readability and/or consistency.
* Navigation
    * Unified navbar logo spacing between Tutorials/Blog pages and Support page.
    * Restyled mobile menu button to transform from hamburger to X when opened, and removed border.
    * Navigation affixed on all pages.
        * Having it static on some mobile pages may have been on purpose. If this was the case to conserve vertical space on smaller screens, we could gain some back by using only the truffle logo on small screens. That way, it could be fixed across all sizes.
    * Fixed nav-collapse on subpages.
        * **Source of bug** was that sub-page layouts contained all html so css and scripts were duplicated. Trimmed down all sub-page layouts to their interiors (usually a container section with the page's name as a class).
* Footer
    * Increased spacing between footer items on moible, specifically logo vs. nav items and attribution vs. signup form.
    * Truffle wordmark now scales with footer.
* Home
    * Moved Truffle logo to navbar.
    * Added navigation to home page.
    * Home page header now 100% height on desktops, auto on mobile;
        * Other items remain but are centered absolutely until mobile, at which point normal layout-flow resumes.
    * Added myself to the team section. :)
    * Set max-width on GitHub logo (300px).
* Documentation
    * Unified mailing list signup form (both on index and contact developers) with main footer.
    * Search form now an input group—no gap between button and input.
    * Fixed GitHub issue #29 (https://github.com/trufflesuite/trufflesuite.github.io/issues/29).
        * **Source of bug** was that metalsmith does not like slashes before hashes.
    * Fixed GitHub issue #51 (https://github.com/trufflesuite/trufflesuite.github.io/issues/51).
        * **Source of bug** was that metalsmith does not like slashes before hashes.
* Blog/Tutorials
    * Unified container sizes between Blog and Tutorials.
    * Made cards and blog post main content full-width and in container.
    * Unified horizontal rule styling to be dotted.
    * Changed Blog and Tutorial background colors to cream for added contrast with navbar.
    * Unified card title fonts and zoom effect with home page.
* Support
    * Stacked life-saver on mobile.

### CODE REVIEW

**Comment by tcoulter** [comment]
Inline feedback:

* Global
    * Slightly altered blog/tutorial card styling for higher contrast. Previously blue text is now black, with read more bolded, since it's the action.
      * **From Tim:** :+1:  
    * Unified transition times when hovering tutorial and blog cards.
      * **From Tim:** :+1:  Didn't know there was a difference.
    * Various spacing adjustments for readability and/or consistency.
      * **From Tim:** Most of these are good I think. I have a few I'd like to chat with you about that I had liked better previously. Thought about typing them but a hangouts chat would be a lot quicker.
* Navigation
    * Unified navbar logo spacing between Tutorials/Blog pages and Support page.
      * **From Tim:** :+1: Like it.
    * Restyled mobile menu button to transform from hamburger to X when opened, and removed border.
      * **From Tim:** :+1: Awesome. I'm not entirely sure this even worked before, so love it.
    * Navigation affixed on all pages.
        * Having it static on some mobile pages may have been on purpose. If this was the case to conserve vertical space on smaller screens, we could gain some back by using only the truffle logo on small screens. That way, it could be fixed across all sizes.
      * **From Tim:** 🤔 I'm not sure if it was on purpose or not, but my gut is it was. Either way, I like the nav how it is, but we should probably make the Truffle logo a tad smaller in this case. 
    * Fixed nav-collapse on subpages.
        * **Source of bug** was that sub-page layouts contained all html so css and scripts were duplicated. Trimmed down all sub-page layouts to their interiors (usually a container section with the page's name as a class).
        * **From Tim:** :+1: I don't quite understand the bug as you described it, might be best for a hangouts chat, but :+1: nonetheless.
* Footer
    * Increased spacing between footer items on moible, specifically logo vs. nav items and attribution vs. signup form.
      * **From Tim:** :+1:
    * Truffle wordmark now scales with footer.
      * **From Tim:** :+1:
* Home
    * Moved Truffle logo to navbar.
      * **From Tim:** :+1:
    * Added navigation to home page.
      * **From Tim:** :+1:
    * Home page header now 100% height on desktops, auto on mobile;
        * Other items remain but are centered absolutely until mobile, at which point normal layout-flow resumes.
      * **From Tim:** :+1: I want the background to become white earlier - will show you in hangouts.
    * Added myself to the team section. :)
      * **From Tim:** :+1: :+1: 
    * Set max-width on GitHub logo (300px).
      * **From Tim:** :+1:
* Documentation
    * Unified mailing list signup form (both on index and contact developers) with main footer.
      * **From Tim:** :+1: Are you on the mailing list yet? If not, can you signup for the list and ensure the form still works?
    * Search form now an input group—no gap between button and input.
      * **From Tim:** :+1:
    * Fixed GitHub issue #29 (https://github.com/trufflesuite/trufflesuite.github.io/issues/29).
        * **Source of bug** was that metalsmith does not like slashes before hashes.
      * **From Tim:** :+1:
    * Fixed GitHub issue #51 (https://github.com/trufflesuite/trufflesuite.github.io/issues/51).
        * **Source of bug** was that metalsmith does not like slashes before hashes.
      * **From Tim:** :+1:
* Blog/Tutorials
    * Unified container sizes between Blog and Tutorials.
      * **From Tim:** :+1:
    * Made cards and blog post main content full-width and in container.
      * **From Tim:** 🤔 Is there a reason you didn't do this for the tutorials? I've grown accustomed to the current look - my guess is you're trying to distinguish between the blog and the tutorials based on how they look? 
    * Unified horizontal rule styling to be dotted.
      * **From Tim:** Delayed :+1: I wasn't sure I liked it but it doesn't look better than what was there. 
    * Changed Blog and Tutorial background colors to cream for added contrast with navbar.
      * **From Tim:** ❓🤔  I have a hard time with this one. The cream works well for the documentation, but I've grown accustomed to the white background. Let's chat on hangouts.
    * Unified card title fonts and zoom effect with home page.
      * **From Tim:** :+1:
* Support
    * Stacked life-saver on mobile.
      * **From Tim:** 🤔 I'm not sure I like this as much. I see what you're going for - looks odd on my phone. Perhaps there's another option. 

-------------------

Overall great job. Lots of loose ends tied up. Here's what we should chat about on hangouts:

- Various spacing adjustments on home page
- Static vs non-static nav on mobile
- Nav background showing up earlier
- Full width blog posts (vs. Tutorials)
- Dotted horizontal rule 
- Cream background for Tutorials / blog posts
- Stacked life saver

**Comment by DiscRiskandBisque** [comment]
* Global
  * Navbar height shrinks to 60px for mobile screens.
  * Navbar white on all pages.
  * Added a mobile-only line break to all pages with a "See a way to make this page better?" link. Previously, an awkward line break could occur between the arrow and the rest of the link text. With the line break in place, the complete link is always on a second line for small screens.
  * Added 1px gray border to footer to help differentiate from cream pages.
* Landing Page
  * Navbar becomes full opacity after any scrolling.
  * Code block in landing page header fills container.
  * Header container (and therefore tagline) original width.
  * Added scroll arrow/button/indicator.
* Blog/Tutorials
  * Code blocks again full-width (noticed they weren't anymore once I centered the pages) and lists fixed on blog and tutorial pages.
* Support
  * Support lifesaver hidden on mobile.

**Comment by tcoulter** [comment]
Alright @DiscRiskandBisque. This is looking sweet. Couple bugs for ya! (Did I tell you I was a tester for a long time?)

- Scroll indicator doesn't disappear for me after the first scroll (Chrome)
- Scroll indicator awkward on vertically small windows (possibly not worth fixing; to reproduce, resize the window vertically until the scroll indicator covers other content):
  screen shot 2017-04-25 at 10 04 26 am

- Cream background has gone away on the documentation. It should stay cream:
  screen shot 2017-04-25 at 10 08 25 am

- Something happened to the blog's header:
  screen shot 2017-04-25 at 10 09 06 am

- Cream has gone away on the Community and Support pages as well. I intended them to stay cream. If you think that should change let me know.
  - http://localhost:9000/support
  - http://localhost:9000/community

**Comment by DiscRiskandBisque** [comment]
* Added scroll indicator fade-out when user scrolls at all.
* Short screens are always a challenge for absolutely centered content like this. As a solution I have it break to auto height, no scroll arrow (essentially mobile behavior) on screens below to 640px in height.
* Fixed cream background on subpages.
* Fixed Blog title, double-checked other Blog/Tutorial styling.

**Pull request merged**
